CREATE TABLE IF NOT EXISTS discussions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  bookTitle VARCHAR(255) NOT NULL,
  author VARCHAR(255) NOT NULL,
  discussionDate DATE NOT NULL,
  participants JSON NOT NULL,
  mainTopics JSON NOT NULL,
  summary TEXT NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci; 